// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5200/' | (string & {});
};

export type ArchiveResponse = {
    /**
     * Unique identifier of the archive.
     */
    id: string;
    /**
     * Current archive status.
     */
    status: JobStatus;
    /**
     * Current archive progress step.
     */
    progressStep: ProgressStep;
    /**
     * Progress percentage from 0 to 100.
     */
    progressPercent: number | string;
    /**
     * Human-readable archive status message.
     */
    message: string;
    /**
     * One-based queue position while waiting.
     */
    queuePosition: null | number | string;
    /**
     * Identifier of the created snapshot, when available.
     */
    snapshotId: null | string;
    snapshotQuality: null | SnapshotQuality;
    /**
     * Failure details, when the archive failed.
     */
    errorMessage: null | string;
    /**
     * Timestamp at which the archive was created, including its UTC offset.
     */
    createdAt: string;
    /**
     * Timestamp at which the archive completed, including its UTC offset.
     */
    completedAt: null | string;
    /**
     * Processing duration in milliseconds.
     */
    durationMilliseconds: number | string;
    /**
     * Storage used by the archived snapshot in bytes.
     */
    storageBytes: number | string;
    /**
     * Number of resources in the archived snapshot.
     */
    resourceCount: number | string;
};

export type CaptureDistributionResponse = {
    /**
     * Matches under text and metadata filters, ignoring capture-time filters.
     */
    total: number | string;
    /**
     * Earliest populated year; null when empty.
     */
    firstYear: null | number | string;
    /**
     * Latest populated year; null when empty.
     */
    lastYear: null | number | string;
    /**
     * Annual capture counts before capture-time filters and pagination.
     */
    years: Array<CaptureYearResponse>;
};

export type CaptureYearResponse = {
    /**
     * Calendar year of persisted capture timestamps.
     */
    year: number | string;
    /**
     * Number of matching captures in this year.
     */
    count: number | string;
};

export type CreateArchiveFileRequest = {
    file: Blob | File;
    /**
     * Original public HTTP or HTTPS URL for the uploaded content.
     */
    originalLink: string;
    /**
     * Title for the snapshot that will be created.
     */
    title: string;
    /**
     * Optional description for the snapshot.
     */
    description?: null | string;
    /**
     * Tags assigned to the snapshot. Submit each tag as a separate form field.
     */
    tags?: null | Array<string>;
};

export type CreateArchiveUrlRequest = {
    /**
     * Public HTTP or HTTPS URL to archive.
     */
    sourceUrl: string;
    /**
     * Title for the snapshot that will be created.
     */
    title: string;
    /**
     * Optional description for the snapshot.
     */
    description?: null | string;
    /**
     * Tags assigned to the snapshot.
     */
    tags?: null | Array<string>;
};

export type IFormFile = Blob | File;

/**
 * Lifecycle status of an archive job.
 */
export enum JobStatus {
    QUEUED = 'QUEUED',
    RUNNING = 'RUNNING',
    COMPLETED = 'COMPLETED',
    FAILED = 'FAILED',
    CANCELLED = 'CANCELLED',
    DISCARDED = 'DISCARDED',
    ABORTED = 'ABORTED'
}

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

/**
 * Processing step of an archive job.
 */
export enum ProgressStep {
    SOURCE_CHECK = 'SOURCE_CHECK',
    LOADING_PAGE = 'LOADING_PAGE',
    LOADING_DYNAMIC_CONTENT = 'LOADING_DYNAMIC_CONTENT',
    SAVING_SNAPSHOT = 'SAVING_SNAPSHOT',
    FINISHED = 'FINISHED'
}

export type SnapshotListResponse = {
    /**
     * Snapshots in the requested page.
     */
    items: Array<SnapshotResponse>;
    /**
     * Total number of matching snapshots.
     */
    total: number | string;
    /**
     * One-based result page number.
     */
    page: number | string;
    /**
     * Number of snapshots per result page.
     */
    pageSize: number | string;
    /**
     * Total number of published snapshots, independent of search filters.
     */
    indexTotal: number | string;
    /**
     * Up to four newest capture timestamps in the published register, independent of search and pagination.
     */
    recentCaptureTimes: Array<string>;
    /**
     * Capture distribution under text and metadata filters, ignoring capture-time filters and pagination.
     */
    captureDistribution: CaptureDistributionResponse;
};

/**
 * Capture-time ordering, with the snapshot ID as a stable tie-breaker.
 */
export enum SnapshotOrder {
    DESC = 'desc',
    ASC = 'asc'
}

/**
 * Completeness of an archived snapshot.
 */
export enum SnapshotQuality {
    COMPLETE = 'COMPLETE',
    INCOMPLETE = 'INCOMPLETE'
}

export type SnapshotResponse = {
    /**
     * Unique identifier of the snapshot.
     */
    id: string;
    /**
     * Archived public source URL.
     */
    sourceUrl: null | string;
    /**
     * Original public URL for uploaded content.
     */
    originalLink: null | string;
    /**
     * Snapshot title.
     */
    title: string;
    /**
     * Optional snapshot description.
     */
    description: null | string;
    /**
     * Completeness of the snapshot.
     */
    quality: SnapshotQuality;
    /**
     * Timestamp at which the snapshot was created, including its UTC offset.
     */
    createdAt: string;
    /**
     * Archive duration in milliseconds.
     */
    durationMilliseconds: number | string;
    /**
     * Storage used by the snapshot in bytes.
     */
    storageBytes: number | string;
    /**
     * Number of resources in the archived snapshot.
     */
    resourceCount: number | string;
    /**
     * Tags assigned to the snapshot.
     */
    tags: Array<string>;
    /**
     * Public URL of the snapshot screenshot.
     */
    screenshotUrl: string;
    /**
     * Public URL of the archived start page.
     */
    contentUrl: string;
};

/**
 * Source used to create an archive job.
 */
export enum SourceType {
    URL = 'URL',
    HTML = 'HTML',
    MHTML = 'MHTML',
    WEBARCHIVE = 'WEBARCHIVE'
}

export type ValidationProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
    errors?: {
        [key: string]: Array<string>;
    };
};

export type GetHealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type GetHealthzResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CreateArchiveData = {
    body: CreateArchiveUrlRequest;
    path?: never;
    query?: never;
    url: '/api/archive';
};

export type CreateArchiveErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type CreateArchiveError = CreateArchiveErrors[keyof CreateArchiveErrors];

export type CreateArchiveResponses = {
    /**
     * OK
     */
    200: ArchiveResponse;
};

export type CreateArchiveResponse = CreateArchiveResponses[keyof CreateArchiveResponses];

export type GetArchiveData = {
    body?: never;
    path: {
        archiveId: string;
    };
    query?: never;
    url: '/api/archive/{archiveId}';
};

export type GetArchiveErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetArchiveError = GetArchiveErrors[keyof GetArchiveErrors];

export type GetArchiveResponses = {
    /**
     * OK
     */
    200: ArchiveResponse;
};

export type GetArchiveResponse = GetArchiveResponses[keyof GetArchiveResponses];

export type StreamArchiveEventsData = {
    body?: never;
    path: {
        archiveId: string;
    };
    query?: never;
    url: '/api/archive/{archiveId}/events';
};

export type StreamArchiveEventsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CancelArchiveData = {
    body?: never;
    path: {
        archiveId: string;
    };
    query?: never;
    url: '/api/archive/{archiveId}/cancel';
};

export type CancelArchiveErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type CancelArchiveError = CancelArchiveErrors[keyof CancelArchiveErrors];

export type CancelArchiveResponses = {
    /**
     * OK
     */
    200: ArchiveResponse;
};

export type CancelArchiveResponse = CancelArchiveResponses[keyof CancelArchiveResponses];

export type ListSnapshotsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Whitespace-separated terms. Every term must match the title, description, source URL, or a tag. At most 20 terms are allowed.
         */
        text?: string;
        /**
         * Exact archived source URL. The value is normalized before matching.
         */
        sourceUrl?: string;
        /**
         * Case-insensitive title substring.
         */
        title?: string;
        /**
         * Case-insensitive description substring.
         */
        description?: string;
        /**
         * Tags that must all be assigned to a matching snapshot. Repeat the query parameter for multiple tags.
         */
        tags?: Array<string>;
        /**
         * Source used to create the snapshot.
         */
        sourceType?: SourceType;
        /**
         * Completeness of the snapshot.
         */
        quality?: SnapshotQuality;
        /**
         * Inclusive start of the capture range as an offset timestamp.
         */
        capturedFrom?: string;
        /**
         * Exclusive end of the capture range as an offset timestamp.
         */
        capturedUntil?: string;
        /**
         * Capture-time ordering: desc (newest first, default) or asc (oldest first). Snapshot IDs use the same direction as a stable tie-breaker.
         */
        order?: SnapshotOrder;
        /**
         * One-based result page number.
         */
        page?: number | string;
        /**
         * Number of snapshots per result page.
         */
        pageSize?: number | string;
    };
    url: '/api/snapshots';
};

export type ListSnapshotsErrors = {
    /**
     * Bad Request
     */
    400: ValidationProblemDetails;
};

export type ListSnapshotsError = ListSnapshotsErrors[keyof ListSnapshotsErrors];

export type ListSnapshotsResponses = {
    /**
     * OK
     */
    200: SnapshotListResponse;
};

export type ListSnapshotsResponse = ListSnapshotsResponses[keyof ListSnapshotsResponses];

export type GetSnapshotData = {
    body?: never;
    path: {
        snapshotId: string;
    };
    query?: never;
    url: '/api/snapshots/{snapshotId}';
};

export type GetSnapshotErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetSnapshotError = GetSnapshotErrors[keyof GetSnapshotErrors];

export type GetSnapshotResponses = {
    /**
     * OK
     */
    200: SnapshotResponse;
};

export type GetSnapshotResponse = GetSnapshotResponses[keyof GetSnapshotResponses];

export type GetSnapshotContentData = {
    body?: never;
    path: {
        snapshotId: string;
        path: string;
    };
    query?: never;
    url: '/api/snapshots/{snapshotId}/content/{path}';
};

export type GetSnapshotContentErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetSnapshotContentError = GetSnapshotContentErrors[keyof GetSnapshotContentErrors];

export type GetSnapshotContentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetSnapshotScreenshotData = {
    body?: never;
    path: {
        snapshotId: string;
    };
    query?: never;
    url: '/api/snapshots/{snapshotId}/screenshot';
};

export type GetSnapshotScreenshotErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetSnapshotScreenshotError = GetSnapshotScreenshotErrors[keyof GetSnapshotScreenshotErrors];

export type GetSnapshotScreenshotResponses = {
    /**
     * OK
     */
    200: unknown;
};
