// <auto-generated />
using System;
using Archive.Core;
using Archive.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Archive.Core.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260909191813_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "types", "job_status", new[] { "ABORTED", "CANCELLED", "COMPLETED", "DISCARDED", "FAILED", "QUEUED", "RUNNING" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "types", "progress_step", new[] { "FINISHED", "LOADING_DYNAMIC_CONTENT", "LOADING_PAGE", "SAVING_SNAPSHOT", "SOURCE_CHECK" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "types", "snapshot_quality", new[] { "COMPLETE", "INCOMPLETE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "types", "source_type", new[] { "HTML", "URL" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Archive.Core.Entities.ArchiveJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("description");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<string>("OriginUrl")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("origin_url");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<ProgressStep>("ProgressStep")
                        .HasColumnType("types.progress_step")
                        .HasColumnName("progress_step");

                    b.Property<SourceType>("SourceType")
                        .HasColumnType("types.source_type")
                        .HasColumnName("source_type");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<JobStatus>("Status")
                        .HasColumnType("types.job_status")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<string>("UploadedObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("uploaded_object_key");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("archive_jobs", "processing");
                });

            modelBuilder.Entity("Archive.Core.Entities.ArchiveJobTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Value")
                        .IsUnique();

                    b.ToTable("archive_job_tags", "processing");
                });

            modelBuilder.Entity("Archive.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasMaxLength(4500)
                        .HasColumnType("character varying(4500)")
                        .HasColumnName("project_key");

                    b.HasKey("Id");

                    b.HasIndex("ProjectKey")
                        .IsUnique();

                    b.ToTable("projects", "archive");
                });

            modelBuilder.Entity("Archive.Core.Entities.Snapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CaptureCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capture_completed_at");

                    b.Property<DateTimeOffset?>("CaptureStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capture_started_at");

                    b.Property<string>("ContentPrefix")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("content_prefix");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("description");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("OriginUrl")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("origin_url");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<SnapshotQuality>("Quality")
                        .HasColumnType("types.snapshot_quality")
                        .HasColumnName("quality");

                    b.Property<int>("ResourceCount")
                        .HasColumnType("integer")
                        .HasColumnName("resource_count");

                    b.Property<SourceType>("SourceType")
                        .HasColumnType("types.source_type")
                        .HasColumnName("source_type");

                    b.Property<long>("StorageBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_bytes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProjectId");

                    b.HasIndex("OriginUrl", "CreatedAt");

                    b.ToTable("snapshots", "archive");
                });

            modelBuilder.Entity("Archive.Core.Entities.SnapshotTag", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("SnapshotId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("snapshot_tags", "archive");
                });

            modelBuilder.Entity("Archive.Core.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("tags", "archive");
                });

            modelBuilder.Entity("Archive.Core.Entities.ArchiveJobTag", b =>
                {
                    b.HasOne("Archive.Core.Entities.ArchiveJob", "Job")
                        .WithMany("Tags")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Archive.Core.Entities.Snapshot", b =>
                {
                    b.HasOne("Archive.Core.Entities.Project", "Project")
                        .WithMany("Snapshots")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Archive.Core.Entities.SnapshotTag", b =>
                {
                    b.HasOne("Archive.Core.Entities.Snapshot", "Snapshot")
                        .WithMany("SnapshotTags")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archive.Core.Entities.Tag", "Tag")
                        .WithMany("SnapshotTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Archive.Core.Entities.ArchiveJob", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Archive.Core.Entities.Project", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Archive.Core.Entities.Snapshot", b =>
                {
                    b.Navigation("SnapshotTags");
                });

            modelBuilder.Entity("Archive.Core.Entities.Tag", b =>
                {
                    b.Navigation("SnapshotTags");
                });
#pragma warning restore 612, 618
        }
    }
}
